### PR TITLE
Upgrade Akka to 1.1.3 and SBT to 0.10.1.

### PR DESCRIPTION
**Pull request by marcweil**
Courtesy of Scalathon with much help from Mark Harrah.
This includes the IDEA project file generator as well.

### CODE REVIEW

**Comment by sirthias** [comment]
Thanks a lot, Marc!
This is indeed somewhat more complex that I imagined it to be.
Would have been difficult for us to figure all this out by ourselves..., so thanks again!

**Comment by marcweil** [comment]
No problem! Glad I could help. I definitely couldn't have done it without Mark's help. Now you have more time to spend on documentation. ;-)

**Comment by sirthias** [comment]
Indeed... :)

I decided to move SBT 0.10 support into its own branch, since quite a few people will still be more accustomed to 0.7.7.
So I'll try to support both for some time, before making the final switch.

**Comment by marcweil** [comment]
Ah yeah sounds like a good idea. Can't really force people to transition from 0.7.7 to 0.10.x quite yet since it's so difficult.

**Pull request merged**
