### PR TITLE
moved to scala 2.11 and provided newer akka/scalatest versions

### PR DESCRIPTION
**Pull request by antonkulaga**
I moved it to scala 2.11 and provided newer akka/scalatest versions

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks @antonkulaga. I think we need to do it a bit differently as we are providing branches for all the possible configurations, so what we need is new branches for spray 1.3/ Akka 2.3.5 / Scala 2.11 which branch off the other spray 1.3 branches and maybe make the spray-can one the default one.

**Comment by mingchuno** [comment]
you can see my fork:
https://github.com/mingchuno/spray-template/tree/on_spray-can_1.3

**Comment by csaltos** [comment]
Thanks mcOr !! ... I finally get my project to work with Scala 2.11 (using Spray 1.3.1 and Akka 2.3.5) ... I also use ReactiveMongo so just in case someone is looking for the "magic" numbers, here my library dependencies:

libraryDependencies ++= {
  val akkaV = "2.3.5"
  val sprayV = "1.3.1"
  Seq(
    "io.spray" %% "spray-can" % sprayV,
    "io.spray" %% "spray-routing" % sprayV,
    "io.spray" %% "spray-testkit" % sprayV % "test",
    "io.spray"            %%  "spray-json"            % "1.2.6",
    "com.typesafe.akka" %% "akka-actor" % akkaV,
    "com.typesafe.akka" %% "akka-testkit" % akkaV % "test",
    "org.specs2" %% "specs2" % "2.4.1" % "test",
    "commons-codec"       %   "commons-codec"         % "1.9",
    "org.reactivemongo"   %%  "reactivemongo"         % "0.10.5.akka23-SNAPSHOT",
    "com.typesafe.scala-logging"        %%  "scala-logging-slf4j"         % "2.1.2"
  )
}

commons-codec and scala-logging are optional but we use them in our project.

Once again, thank you very much mcOr and Johannes Rudolph for the Spray templates and your code. I hope the Scala 2.11 enabled template version code will be merged and available soon.

**Comment by jrudolph** [comment]
Thanks, all, for your input. I created new branches for Scala 2.11 and made a 2.11 one the default.

**Pull request closed without merging**
